apiVersion: v1
kind: ConfigMap
metadata:
  name: config-defaults
  namespace: tekton-pipelines
data:
  helmTemplateRemoveMe: |
    {{- if .Values.configDefaults -}}{{- toYaml .Values.configDefaults | nindent 2 }}{{ end }}
