apiVersion: v1
kind: ConfigMap
metadata:
  name: feature-flags
  namespace: tekton-pipelines
helmTemplateRemoveMe: |
  {{- if .Values.featureFlags -}}{{- toYaml .Values.featureFlags | nindent 2 }}{{ end }}
